<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/bower_components/bootstrap/dist/css/bootstrap.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/bower_components/Ionicons/css/ionicons.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/bower_components/select2/dist/css/select2.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/dist/css/AdminLTE.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/dist/css/skins/_all-skins.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/plugins/pace/pace.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/plugins/timepicker/bootstrap-timepicker.min.css'}}">
<link rel="stylesheet" href="{{'https://cdn.queensherainfotech.com/adminltev2/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css'}}">
<link rel="stylesheet" href="{{'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'}}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
